[package]
name = "get_profile"
version = "0.1.0"
edition = "2021"

[dependencies]
bisky = { path = "../../" }
clap = { version = "4.2.2", features = ["derive"] }
serde_json = "1.0.96"
tokio = { version = "1.27.0", features = ["macros", "rt-multi-thread"] }
url = "2.3.1"
